"""CPK Companion FAP (CFC) host-side module."""

from .module import (
    flipper_cfc_call,
    cfc_send_raw_frame,
    pack_cfc_frame,
    CfcRemoteError,
    CfcTimeoutError,
    CfcProtocolError,
    CFC_MAGIC,
    CFC_VERSION,
    CFC_HEADER_SIZE,
    CFC_MAX_FRAGMENT_PAYLOAD,
    CFC_MAX_TRANSACTION,
    OP_PING,
    OP_META_CAPABILITIES,
    OP_META_VERSION,
    OP_RESET,
    OP_ERROR,
    ERR_BAD_FRAME,
    ERR_BAD_FRAGMENT,
    ERR_PAYLOAD_TOO_LARGE,
    ERR_OUT_OF_MEMORY,
    ERR_BUSY,
    ERR_BAD_PAYLOAD,
    ERR_UNKNOWN_OPCODE,
    ERR_INTERNAL,
)

__all__ = [
    "flipper_cfc_call",
    "cfc_send_raw_frame",
    "pack_cfc_frame",
    "CfcRemoteError",
    "CfcTimeoutError",
    "CfcProtocolError",
    "CFC_MAGIC",
    "CFC_VERSION",
    "CFC_HEADER_SIZE",
    "CFC_MAX_FRAGMENT_PAYLOAD",
    "CFC_MAX_TRANSACTION",
    "OP_PING",
    "OP_META_CAPABILITIES",
    "OP_META_VERSION",
    "OP_RESET",
    "OP_ERROR",
    "ERR_BAD_FRAME",
    "ERR_BAD_FRAGMENT",
    "ERR_PAYLOAD_TOO_LARGE",
    "ERR_OUT_OF_MEMORY",
    "ERR_BUSY",
    "ERR_BAD_PAYLOAD",
    "ERR_UNKNOWN_OPCODE",
    "ERR_INTERNAL",
]
