// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IsLockedRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnlockRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusSubscribeRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusUnsubscribeRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Status {
    #[prost(bool, tag = "1")]
    pub locked: bool,
}
